### ISSUE TITLE
[SEVERE] Could not load 'plugins/RealisticBiomes.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by ttk2** [WildWeazel/RealisticBiomes#3]
06:12:39 [SEVERE] Could not load 'plugins/RealisticBiomes.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:255)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:132)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:279)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:257)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:404)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:214)
        at java.util.zip.ZipFile.<init>(ZipFile.java:144)
        at java.util.jar.JarFile.<init>(JarFile.java:152)
        at java.util.jar.JarFile.<init>(JarFile.java:116)
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:243)
        ... 8 more

**Comment by artcg** [comment]
Did you use this jar file? (https://github.com/WildWeazel/RealisticBiomes/blob/master/RealisticBiomes.jar)
I tried running on a spigot server and it worked for me

**Comment by ttk2** [comment]
how should I download it?

**Comment by artcg** [comment]
Click 'raw' from the page I linked you and it should prompt you to download it http://i.imgur.com/ZnCeA0J.png

**Comment by ttk2** [comment]
ok, seems to work fine now, sorry for the trouble.
