### ISSUE TITLE
Could not pass event PlayerInteractEvent to RealisticBiomes v0.2

### ISSUE THREAD

**Issue by ttk2** [WildWeazel/RealisticBiomes#4]
Could not pass event PlayerInteractEvent to RealisticBiomes v0.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
        at net.minecraft.server.v1_4_6.PlayerInteractManager.interact(PlayerInteractManager.java:376)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:656)
        at net.minecraft.server.v1_4_6.Packet15Place.handle(SourceFile:58)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:585)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:481)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:416)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at com.untamedears.realisticbiomes.listener.GrowListener.onPlayerInteract(GrowListener.java:255)
        at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 16 more

**Comment by artcg** [comment]
Fixed in this pull request 

https://github.com/WildWeazel/RealisticBiomes/pull/5

**Comment by ttk2** [comment]
cool, its online now.

**Comment by WildWeazel** [comment]
Merged pull request. New jar contains the fix.
